### ISSUE TITLE
License requested

### ISSUE THREAD

**Issue by cboulay** [labstreaminglayer/liblsl-Matlab#1]
Hi @chkothe, a user has requested a license for this repo. As you wrote most of it, do you mind adding one, or giving me permission to add one (MIT?) on your behalf?

**Comment by sterlingcrispin** [comment]
Hi @chkothe curious if you saw this and could add an MIT license, thanks!

**Comment by sheljohn** [comment]
Hello @chkothe, just a bump about this: would you please be able to add a license to this repository?

**Comment by jhadida** [comment]
Looking at the [contributors](https://github.com/labstreaminglayer/liblsl-Matlab/graphs/contributors), it actually looks like the main ones are @xloem , @tstenner , and you @cboulay.
If @chkothe is not responsive, would it please be possible to sort this out between the three of you?

**Comment by dmedine** [comment]
If I recall, github notifications are not a great way to get chkothe's attention. liblsl is, of course, MIT licensed. I would assume that this should apply to liblsl-Matlab. I will ping chkothe directly and ask if he has any objections.

**Comment by cboulay** [comment]
I added the MIT license file. Anything that was once part of the google code repository has inherited an MIT license and remains licensed that way unless explicitly changed.
