### ISSUE TITLE
Can't find up-to-date build of library file for MATLAB

### ISSUE THREAD

**Issue by iripuga** [labstreaminglayer/liblsl-Matlab#11]
Hi, I have checked all around the place for ` liblsl64.so` and `liblsl64.so.1.4.0` for 64-bit MATLAB on Linux which are specified in `README.md`. I also tried to find `liblsl64.dylib` and `liblsl64.1.4.0.dylib` for 64-bit MATLAB on MacOS, but again unsuccefully. Can anyone give me some guidance where I could find those files or which files on [release page](https://github.com/sccn/liblsl/releases) to use for Linux and MacOS.

**Comment by cboulay** [comment]
On the release page, click on the little "Assets" expansion and you should see a bunch of files there. For Linux you'll need to download a [.deb file](https://unix.stackexchange.com/a/159114). For MacOS, it's one of the .tar.bz2 files.

**Comment by tstenner** [comment]
It depends on which distribution you're running. For Ubuntu LTS releases, there's the `liblsl-1.13.1-Linux64-*codename*.deb`, but the bionic deb should work on most distributions.

**Comment by iripuga** [comment]
Hi, I succesfully installed `bionic.deb ` on Ubuntu, thank you for that. However MATLAB still can't find `lsl_loadlib()` function. I get the following error in MATLAB command line once I try to call script `ReceiveData:`

`Error using lsl_loadlib (line 70)`
`Error loading the liblsl library: Undefined function 'lsl_loadlib_' for input arguments of type 'char'.`

`Error in ReceiveData (line 5)`
`lib = lsl_loadlib();`

Any help or ideas would be kindly appreciated.
