### ISSUE TITLE
404 link in Readme.md

### ISSUE THREAD

**Issue by LJGz** [labstreaminglayer/liblsl-Matlab#12]
README.md in [https://github.com/labstreaminglayer/liblsl-Matlab](https://github.com/labstreaminglayer/liblsl-Matlab) contains the link [https://github.com/sccn/labstreaminglayer/blob/master/doc/BUILD.md#note-about-architectures--binaries](https://github.com/sccn/labstreaminglayer/blob/master/doc/BUILD.md#note-about-architectures--binaries) which is a 404.

**Comment by tstenner** [comment]
Thanks, I've fixed the link. Still, the Matlab code (and the binaries) needs some changes for the newer liblsl versions.
