### ISSUE TITLE
How to view the marker stream output

### ISSUE THREAD

**Issue by balandongiv** [labstreaminglayer/liblsl-Matlab#13]
Dear All
I have followed the [tutorial](https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/SendStringMarkers.m) deligently. However, I'm unable to view the marker stream output. While the [tutorial 2](https://github.com/sccn/labstreaminglayer/wiki/Tutorial-3.-Generate-your-own-data-streams-using-MATLAB) showed how to open the output, but it require external software. May I know how to open the output, maybe by using only a few line.

Thanks in advance
Software: MATLAB.

**Comment by dmedine** [comment]
Any of the APIs have example programs/scripts that can receive and print string markers (e.g. https://github.com/labstreaminglayer/liblsl-Python/blob/96128ccc660de3776eff0cfe54ea3be33c7f01cb/pylsl/examples/ReceiveStringMarkers.py)

There is also a little-known viewer available on the SCCN ftp called streamviewer. It is part of the 'mobi_utils' package: ftp://sccn.ucsd.edu/pub/software/LSL/Mobi_Utils/.

**Comment by balandongiv** [comment]
Thanks for the quick reply @dmedine .
The link you provide is for Python. Appreciate if you can direct to MATLAB base example.

**Comment by cboulay** [comment]
@balandongiv the Matlab examples are in this repository in the folder called "examples".
https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/ReceiveStringMarkers.m

**Comment by balandongiv** [comment]
Thanks for link @cboulay.
I still try to understand how everything work.

Say we are able to push the marker as below, (from the [tutorial](https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/ReceiveStringMarkers.m))

`outlet.push_sample({mrk});   % note that the string is wrapped into a cell-array`

Next, to extract the marker. 
How to setup the `outlet` to view the marker as per example depicted in the this [tutorial](https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/ReceiveStringMarkers.m).

For example, where to position the handle `outlet` in the line below
```

while isempty(result)
    result = lsl_resolve_byprop(lib,'type','Markers'); end
```

I can understand both the example [ReceiveStringMarkers](https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/ReceiveStringMarkers.m) and [SendStringMarkers](https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/SendStringMarkers.m), but unable to digest when both of them work together. Specifically, once we sent the marker, then how to extract it later.
