### ISSUE TITLE
Library not working for Simulink

### ISSUE THREAD

**Issue by xtream111** [labstreaminglayer/liblsl-Matlab#18]
I used the link provided in this repo about the Simulink version of lsl. However, when I run the model with that all Matlab windows close and crash.

I don't know where to post this but does anyone know how to resolve this issue

**Comment by cboulay** [comment]
I assume you mean you followed the link to SimBSI. That is independent of this project. You'll have to ask there: https://bitbucket.org/neatlabs/simbsi/wiki/Home There's a JIRA link on the left.
Or you can try e-mailing the author Alejandro Ojeda
