### ISSUE TITLE
Build the mex files

### ISSUE THREAD

**Issue by samvanb11** [labstreaminglayer/liblsl-Matlab#19]
I am trying to download and install 'from source'.

I am having issues with step 3. Build the mex files

I am successfully running `build_mex` all the files are up to date. 

But when I run `matlab -nodesktop -nosplash -r 'build_mex'` I get the error message:
`Attempt to execute SCRIPT matlab as a function:
C:\Program Files\MATLAB\R2019b\toolbox\matlab\general\matlab.m`

I am using a Windows PC with Matlab version R2019b. 

Is anybody able to help me?

Thanks,
Sam

**Comment by dmedine** [comment]
Maybe this can help?
https://au.mathworks.com/matlabcentral/answers/93148-why-do-i-receive-the-error-attempt-to-execute-script-filename-as-a-function

If you can build all the mex files, though, what is your issue exactly? Why this extra step?

**Comment by samvanb11** [comment]
Thanks for the advice,

I now have it working
