### ISSUE TITLE
Error getting the data from the inlet

### ISSUE THREAD

**Issue by Kuritzu** [labstreaminglayer/liblsl-Matlab#24]
In this code https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/ReceiveData.m, im able to get the inlet set with the stream but no data is printed and the function never ends. Any tips on what might that be?

**Comment by dmedine** [comment]
Is the outlet you are connected with sending data? There is a nice visualization tool available here: https://www.brainproducts.com/downloads.php?kid=40&tab=3 to help you diagnose.

**Comment by Kuritzu** [comment]
> Is the outlet you are connected with sending data? There is a nice visualization tool available here: https://www.brainproducts.com/downloads.php?kid=40&tab=3 to help you diagnose.

I think so, when I boot OpenSignals, it shows data. I will give a look at the link you provided, and give some update. Thanks

**Comment by Kuritzu** [comment]
So the software gives me this feedback. I assume the stream is not forwarding the data properly. It keeps giving me the same behaviour in a loop.
![errorLsl](https://user-images.githubusercontent.com/58485583/109425531-95ee7500-79e0-11eb-9c17-22dc518fe849.png)

Do you have any advice on how to solve it?

**Comment by Kuritzu** [comment]
Update

I managed to get the data, but I don't seem to be getting microVolts value that I need. Any tip on how to get it?
