### ISSUE TITLE
liblsl64.dll

### ISSUE THREAD

**Issue by MSA8D8** [labstreaminglayer/liblsl-Matlab#7]
Hi 

I tried to use the LSL by Matlab in Windows 10 PC.
Then, I got the error message below.

`>> lsl_loadlib
エラー: lsl_loadlib (line 62)
Apparently the file
"D:\Sasaki\SasakiCode\liblsl-Matlab\bin\liblsl64.dll" is missing on
your computer. Cannot load the lab streaming layer.
`

So, I read the trouble shooting in the "liblsl-Matlab" page.
Then, I got another error message.

`>> build_mex
エラー: build_mex (line 18)
liblsl64.dll not found in bin/
`

Could you please tell me how to solve this problem

Thank you in advance.

**Comment by dmedine** [comment]
Please provide exact details about how you encountered this error. What
commands did you run in Matlab? What operating system are you using? Which
version if liblsl-Matlab do you have?

**Comment by MSA8D8** [comment]
Thank you for your response and sorry for my late response.

The OS of my computer is Windows10 and the version of "liblsl-Matlab" is this link, https://github.com/labstreaminglayer/liblsl-Matlab

And, here are the details of the commands I ran.

Thank you in advance.


>> lsl_loadlib
'lsl_loadlib' is not found in the current folder or on the MATLAB path,
but exists in:
    D:\Sasaki\SasakiCode\labstreaminglayer\LSL\liblsl-Matlab

Change the MATLAB current folder or add its folder to the MATLAB path.
 
>> lsl_loadlib
Undefined function or variable 'lsl_loadlib_'.

Error in lsl_loadlib (line 65)
    hlib = lsl_loadlib_(dllpath);
 
>> build_mex
Error using mex
MEX cannot find library 'lsl64', specified with the -l option.
 MEX searched for a file with one of the following names:
 liblsl64.lib
 lsl64.lib
 Verify the library name is correct. If the library is not
 on the existing path, specify the path with the -L option.


Error in build_mex (line 30)
		mex('-I../../liblsl/include','-L.', libs{:}, ['../mex/',
        f.name]);

**Comment by tstenner** [comment]
Just to be sure: did you put `liblsl64.dll` from the [liblsl-1.13.0-Win64.7z](https://github.com/sccn/liblsl/releases) package in the `bin/` subfolder?

**Comment by MSA8D8** [comment]
Hi.

I tried using liblsl64.dll from your link, but the situation is the same as before.

>> build_mex
Error using mex
MEX cannot find library 'lsl64', specified with the -l option.
 MEX searched for a file with one of the following names:
 liblsl64.lib
 lsl64.lib
 Verify the library name is correct. If the library is not
 on the existing path, specify the path with the -L option.


Error in build_mex (line 30)
		mex('-I../../liblsl/include','-L.', libs{:}, ['../mex/',
        f.name]);

**Comment by dmedine** [comment]
It looks like liblsl64.lib is not being found. The mex compiler needs 
that file for the symbols. The dll is only used at runtime.

**Comment by MSA8D8** [comment]
Thank you for your response, @dmedine 

Do you know where liblsl64.lib can be downloaded?

**Comment by MSA8D8** [comment]
I found liblsl64.lib file in the link below.
https://github.com/sccn/liblsl/releases/download/1.13.0-b12/liblsl-tests-1.13.0-Win64.7z

But, I am facing with another error message.

Thanks.

>> build_mex
Building with 'MinGW64 Compiler (C)'.
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c: In function 'mexFunction':
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c:32:10: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     func = (lsl_append_child_t*)*pTmp;
          ^
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c:39:5: warning: implicit declaration of function 'mxGetNChars_700' [-Wimplicit-function-declaration]
     mxGetNChars_700(prhs[2], str, str_len+1);
     ^~~~~~~~~~~~~~~
Error using mex
'D:\Sasaki\SasakiCode\liblsl-Matlab\bin\lsl_append_child.mexw64' is
compiled with incompatible options '-compatibleArrayDims' and
-R2017b'. For more information, see MEX file compiled with
incompatible options.
Error in build_mex (line 30)
		mex('-I../../liblsl/include','-L.', libs{:}, ['../mex/',
        f.name]);







I checked the version of mex configuration, too.

>> mex -setup
MEX configured to use 'MinGW64 Compiler (C)' for C language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.

>> To choose a different language, select one from the following:
 mex -setup C++ 
 mex -setup FORTRAN

**Comment by dmedine** [comment]
Latest build is here: https://github.com/sccn/liblsl/releases

You need to make sure that the .lib and the .dll are from the same build.

**Comment by tstenner** [comment]
> Error using mex
'D:\Sasaki\SasakiCode\liblsl-Matlab\bin\lsl_append_child.mexw64' is
compiled with incompatible options '-compatibleArrayDims' and
-R2017b'. For more information, see MEX file compiled with
incompatible options.

So we're getting a step closer. Could you delete everything in bin and run `build_mex` again?

**Comment by MSA8D8** [comment]
Thank you both.

@dmedine I tried to use both files from the latest version of liblsl-1.13.0-Win64.7z in the link. But, nothing was improved.

@tstenner I retried running again after deleting all the files in the "bin" folder except for .dll and .lib file, but the same error message was left.

**Comment by MSA8D8** [comment]
I tried to use the latest lib and dll files uploaded in the link below.
https://github.com/sccn/liblsl/releases/tag/1.13.0-b13 

Here is the result of running "build_mex.m" in Matlab R2018b, Windows10. 

>> build_mex
Building with 'MinGW64 Compiler (C)'.
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c: In function 'mexFunction':
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c:32:10: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     func = (lsl_append_child_t*)*pTmp;
          ^
D:\Sasaki\SasakiCode\liblsl-Matlab\mex\lsl_append_child.c:39:5: warning: implicit declaration of function 'mxGetNChars_700' [-Wimplicit-function-declaration]
     mxGetNChars_700(prhs[2], str, str_len+1);
     ^~~~~~~~~~~~~~~

Error using mex
'D:\Sasaki\SasakiCode\liblsl-Matlab\bin\lsl_append_child.mexw64' is compiled with incompatible
options '-compatibleArrayDims' and -R2017b'. For more information, see MEX file compiled with
incompatible options.

Error in build_mex (line 30)
		mex('-I../../liblsl/include','-L.', libs{:}, ['../mex/', f.name]);

**Comment by mgrivich** [comment]
I have built a release at https://github.com/labstreaminglayer/liblsl-Matlab/releases/tag/1.13.0-b13. Please try it out. You should not need any other dlls, mex files, etc.

**Comment by mgrivich** [comment]
Run the matlab commands from inside the downloaded folder (or add it to your matlab path).

**Comment by MSA8D8** [comment]
@mgrivich Thank you for your comment.
Here is the result of what I did after adding the folder in your link into "bin" folder of mine.
Is this correct result ??

Thank you very much

>> lsl_loadlib

ans = 

  struct with fields:

                       hlib: 140714048159744
       lsl_protocol_version: 140714048322976
        lsl_library_version: 140714048322960
            lsl_local_clock: 140714048238752
            lsl_resolve_all: 140714048323008
         lsl_resolve_byprop: 140714048324608
         lsl_resolve_bypred: 140714048323712
      lsl_create_streaminfo: 140714048368256
     lsl_destroy_streaminfo: 140714048368960
               lsl_get_name: 140714048369136
               lsl_get_type: 140714048369248
      lsl_get_channel_count: 140714048369024
      lsl_get_nominal_srate: 140714048369152
     lsl_get_channel_format: 140714048369040
          lsl_get_source_id: 140714048369232
            lsl_get_version: 140714048369296
         lsl_get_created_at: 140714048369056
                lsl_get_uid: 140714048369264
         lsl_get_session_id: 140714048369200
           lsl_get_hostname: 140714048369104
               lsl_get_desc: 140714048369072
                lsl_get_xml: 140714048369312
          lsl_create_outlet: 140714048363424
         lsl_destroy_outlet: 140714048363552
          lsl_push_sample_f: 140714048367328
         lsl_push_sample_ft: 140714048367344
        lsl_push_sample_ftp: 140714048367360
          lsl_push_sample_d: 140714048367280
         lsl_push_sample_dt: 140714048367296
        lsl_push_sample_dtp: 140714048367312
          lsl_push_sample_l: 140714048367376
         lsl_push_sample_lt: 140714048367392
        lsl_push_sample_ltp: 140714048367408
          lsl_push_sample_i: 140714048367376
         lsl_push_sample_it: 140714048367392
        lsl_push_sample_itp: 140714048367408
          lsl_push_sample_s: 140714048367424
         lsl_push_sample_st: 140714048367440
        lsl_push_sample_stp: 140714048367456
          lsl_push_sample_c: 140714048367232
         lsl_push_sample_ct: 140714048367248
        lsl_push_sample_ctp: 140714048367264
        lsl_push_sample_str: 140714048367472
       lsl_push_sample_strt: 140714048367488
      lsl_push_sample_strtp: 140714048367504
        lsl_push_sample_buf: 140714048366704
       lsl_push_sample_buft: 140714048366736
      lsl_push_sample_buftp: 140714048366768
          lsl_push_sample_v: 140714048367968
         lsl_push_sample_vt: 140714048368032
        lsl_push_sample_vtp: 140714048368080
         lsl_have_consumers: 140714048363696
     lsl_wait_for_consumers: 140714048368144
               lsl_get_info: 140714048363600
           lsl_create_inlet: 140714048345424
          lsl_destroy_inlet: 140714048345584
           lsl_get_fullinfo: 140714048345632
            lsl_open_stream: 140714048345776
           lsl_close_stream: 140714048345392
        lsl_time_correction: 140714048348688
          lsl_pull_sample_f: 140714048347760
          lsl_pull_sample_d: 140714048347744
          lsl_pull_sample_l: []
          lsl_pull_sample_i: 140714048347776
          lsl_pull_sample_s: 140714048347808
          lsl_pull_sample_c: 140714048347728
        lsl_pull_sample_str: 140714048347824
        lsl_pull_sample_buf: 140714048347120
          lsl_pull_sample_v: 140714048348448
      lsl_samples_available: 140714048348544
            lsl_first_child: 140714048370368
             lsl_last_child: 140714048370464
           lsl_next_sibling: 140714048370544
       lsl_previous_sibling: 140714048370960
                 lsl_parent: 140714048370656
                  lsl_child: 140714048370176
         lsl_next_sibling_n: 140714048370592
     lsl_previous_sibling_n: 140714048371008
                  lsl_empty: 140714048370320
                lsl_is_text: 140714048370416
                   lsl_name: 140714048370512
                  lsl_value: 140714048371376
            lsl_child_value: 140714048370240
          lsl_child_value_n: 140714048370272
     lsl_append_child_value: 140714048369984
    lsl_prepend_child_value: 140714048370768
        lsl_set_child_value: 140714048371184
               lsl_set_name: 140714048371280
              lsl_set_value: 140714048371328
           lsl_append_child: 140714048369920
          lsl_prepend_child: 140714048370704
            lsl_append_copy: 140714048370096
           lsl_prepend_copy: 140714048370880
         lsl_remove_child_n: 140714048371136
           lsl_remove_child: 140714048371072
     lsl_set_postprocessing: 140714048348592
                 on_cleanup: [1×1 onCleanup]

**Comment by MSA8D8** [comment]
And, I tried to run and am faced with another error message below.
I don't know whether this result is right or not and why this error happened.

Thank you, too.

>> lsl_streaminfo
Warning: The following error was caught while executing 'lsl_streaminfo' class destructor:
Error using lsl_destroy_streaminfo
The field does not seem to exist.

Error in lsl_streaminfo/delete (line 89)
            lsl_destroy_streaminfo(self.LibHandle,self.InfoHandle);

Error in lsl_streaminfo (line 18)
        function self =
        lsl_streaminfo(lib,name,type,channelcount,samplingrate,channelformat,sourceid) 
> In lsl_streaminfo (line 18) 
Not enough input arguments.

Error in lsl_streaminfo (line 46)
            self.LibHandle = lib;

**Comment by mgrivich** [comment]
Yes, that is what the lib struct looks like. Those are pointers to members (a C thing) so not really something you should be looking at or manipulating.

**Comment by mgrivich** [comment]
When you load the library, make sure that the third argument (keep_persistent) is true if you are running from the command line. I think that is what is causing the error, but I can't test from here.

Or you can make a function like this: https://github.com/labstreaminglayer/liblsl-Matlab/blob/master/examples/SendData.m

**Comment by MSA8D8** [comment]
@mgrivich Thank you very much for your help.
I really appreciate your kindness!
I am finally able to run the script what I want to use with LSL.

And, I want to say thank you both for @dmedine and @tstenner, too

Thanks a lot !!!
